version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: shortener_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: shortener
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 983b10b1c56fa28ca33684d9d903f7a8

  api:
    build: .
    container_name: shortener_api
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
    env_file:
      - .env